# Generated by Django 3.1.7 on 2021-04-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysalary.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('years_at_company', models.PositiveIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('highest_academic_level_attained', models.CharField(choices=[('N', 'None'), ('G', 'Grade School'), ('H', 'High School'), ('A', 'Associate Degree'), ('B', "Bachelor's Degree"), ('M', "Master's Degree"), ('D', 'Doctorate')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysalary.company')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysalary.level')),
            ],
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysalary.company')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysalary.level')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysalary.compensation')),
            ],
        ),
    ]
