# Generated by Django 3.1.7 on 2021-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='contribution',
            name='datetime_of_contribution',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
