# Generated by Django 3.1.7 on 2021-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalary', '0004_auto_20210523_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='years_at_company',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='years_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
