# Generated by Django 3.1.7 on 2021-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalary', '0005_auto_20210523_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='bonus',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
