# Generated by Django 3.1.7 on 2021-06-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysalary', '0006_auto_20210523_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ('-datetime_of_contribution',)},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='compensation',
        ),
        migrations.AddField(
            model_name='certificate',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysalary.contribution'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
    ]
